### ISSUE TITLE
asdf-esy

### ISSUE THREAD

**Issue by schutm** [asdf-community/asdf-esy#1]
Hi @imbsky,

I've got an initial version over at https://gitlab.com/schutm/asdf-esy. Feel free to move it over to here (I couldn't commit to the asdf-esy repo).

**Comment by imbsky** [comment]
@schutm I just moved it to GitHub. By the way, may we manage it on GitHub? (I thought you don't like GitHub)

**Comment by schutm** [comment]
No problem to manage it on github. For a few years gitlab had same advantages (like build-in workflows and continuous integration and free private repos).

**Comment by imbsky** [comment]
🙆‍♂️

**Comment by imbsky** [comment]
@all-contributors please add @schutm for code doc
